version: "3.3"
services:
    api:
        image: orgsinfo/deck:node
        container_name: deck-node
        environment:
            - EVENTDECK_COOKIE_NAME=login
            - EVENTDECK_COOKIE_PASSWORD=44oJ1EoP0fR5BKoAmtDD6C1mCZzHTFYq9LDxt0EgaRQFEP6jkEix1Xa51Wq591nVOQ5d3XAjZWzIKlEYFZf5V7Rr52ilKPHxcZEDvupEoPY4JG0reyYSKHR2056VDMvDUFCH2sn55uNAKgGhWfQrOtnIexfO63feCYSdcxGcdCGZz86vT3bfJCbNZgFgVIkTg2gm3YFUxzzgUmDqkiNfv2nQcVfNaQP0UanEbLKiEedq5o1B6WzLYNvc37eycMsB
            - EVENTDECK_FACEBOOK_APP_SECRET=9f027c52e00bc3adbabcd926a3c95b97
            - EVENTDECK_FACEBOOK_APP_ID=457207507744159
            - EVENTDECK_MONGO_URL=mongodb://db:27017/deck
            - EVENTDECK_HOST=0.0.0.0
            - EVENTDECK_PORT=8080
            - EVENTDECK_URL=http://localhost:8080
        ports:
            - 8080:8080
        links:
            - mongodb:db
        depends_on:
            - mongodb
    mongodb:
        image: mongo:2.7
        container_name: mongodb-2.7
        command: mongod
        volumes:
            # change the first path (prefixing ":") if you want to store on another location
            - ~/Documents/sinfo/mongoData:/data/db
        ports:
            - 27017:27017